# @package _global_

model:
  type: 'dilated_conv_ed'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true
  use_future_covariates: true


model_configs:
  cat_emb_dim: 16
  hidden_RNN: 32
  num_layers_RNN: 4
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  use_bn: false
  dropout_rate: 0.25
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.1
  loss_type: 'l1'
  use_cumsum: false
  use_bilinear: false

train_config:
  batch_size: 64
  max_epochs: 500
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
