#models: ['config_used/attention.yaml','config_used/persistent.yaml','config_used/linear.yaml','config_used/dlinear.yaml','config_used/nlinear.yaml','config_used/lstm.yaml','config_used/gru.yaml']
models: 'config_pollen'
dirpath: "/home/agobbi/Projects/ExpTS/pollen"
set: 'test'
name: 'prova'
rescaling: true
batch_size: 128
