models: ['config_incube/config_used/tft2_test_1_loss_type=std_normpersistence_weight=1.yaml','config_incube/config_used/crossformer_test_1_loss_type=std_penpersistence_weight=10.yaml','config_incube/config_used/mymodel_test_1.yaml','config_incube/config_used/gru_gru_1.yaml','config_incube/config_used/stacked_stacked_1_loss_type=l1.yaml']
#models: 'config_incube'
dirpath: "/home/agobbi/Projects/ExpTS/incube"
set: 'test'
name: 'prova'
rescaling: true
batch_size: 128
