dataset:
  dataset: weather
  path: /home/agobbi/Projects/ExpTS/data
scheduler_config:
  gamma: 0.1
  step_size: 100
optim_config:
  lr: 0.0001
  weight_decay: 0.01
model_configs:
  past_steps: 16
  future_steps: 16
  quantiles: []
  past_channels: 21
  future_channels: 1
  embs:
  - 24
  out_channels: 1
  d_model: 128
  cat_emb_dim: 32
  num_heads: 16
  dropout: 0.3
  n_layer_encoder: 12
  n_layer_decoder: 8
split_params:
  perc_train: 0.7
  perc_valid: 0.1
  range_train: null
  range_validation: null
  range_test: null
  shift: 1
  starting_point: null
  skip_step: 1
  past_steps: 16
  future_steps: 16
train_config:
  dirpath: /home/agobbi/Projects/ExpTS/weights/attention/weather/1
  num_workers: 0
  auto_lr_find: true
  devices:
  - 0
  batch_size: 256
  max_epochs: 250
inference:
  output_path: /home/agobbi/Projects/ExpTS
  load_last: true
  batch_size: 200
  num_workers: 4
  set: validation
  rescaling: true
model:
  type: attention
ts:
  name: weather
  version: 1
  enrich:
  - hour
  use_covariates: true
