---
cl:
  data: '/storage/DSIP/edison/data/edison/processed.pkl'
  folder: '/storage/DSIP/edison/anmartinelli/directTsf/'
  save: '/storage/DSIP/edison/anmartinelli/directTsf/direct_'
  direct: 'direct_'

loc:
  data: '../../../data/edison/processed.pkl'
  folder: '../'
  save: '../direct_'
  direct: 'direct_'