# @package _global_

model:
  type: 'autoformer'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['']
  use_covariates: false



model_configs:
  d_model: 64
  kernel_size: 3
  n_layer_encoder: 5
  n_layer_decoder: 5
  label_len: 12
  n_head: 8
  dropout_rate: 0.25
  factor: 5
  hidden_size: 128
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.010
  loss_type: 'l1'

train_config:
  batch_size: 64
  max_epochs: 400
            
split_params:
  shift: ${model_configs.label_len}
  keep_entire_seq_while_shifting: true
