# @package _global_

model:
  type: 'linear'
  retrain: true
ts:
  name: 'test2'
  version: 1
  enrich: []
  use_covariates: true

model_configs:
  cat_emb_dim: 512
  kernel_size: 25
  sum_emb: true
  hidden_size: 2048
  kind: 'dlinear'
  dropout_rate: 0.5
  use_bn: false  
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  simple: true

train_config:
  batch_size: 64
  max_epochs: 600          
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'