# @package _global_

model:
  type: 'rnn'
  retrain: true
ts:
  name: 'gru'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  cat_emb_dim: 128
  hidden_RNN: 128
  num_layers_RNN: 2
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  use_bn: true  
  optim: torch.optim.SGD
  activation: torch.nn.PReLU
  dropout_rate: 0.5
  persistence_weight: 10.010
  loss_type: 'l1'
  remove_last: true

train_config:
  batch_size: 128
  max_epochs: 1000
            
