# @package _global_

model:
  type: 'informer'
  retrain: true
ts:
  name: 'test3'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  d_model: 32
  hidden_size: 64
  n_layer_encoder: 4
  n_layer_decoder: 4
  n_head: 4
  dropout_rate: 0.25
  optim: torch.optim.Adam
  activation: torch.nn.ReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  remove_last: false

train_config:
  batch_size: 64
  max_epochs: 1000
            
