# @package _global_

model:
  type: 'itransformer'
  retrain: true
ts:
  name: 'anomalie'
  version: 1
  enrich: []
  use_covariates: false


model_configs:
  d_model: 16
  n_head: 4
  hidden_size: 16
  dropout_rate: 0.5
  n_layer_decoder: 4
  use_norm: True
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.GELU
  class_strategy: 'average' #projection/average/cls_token

train_config:
  batch_size: 32
  max_epochs: 600
            
