# @package _global_

model:
  type: 'itransformer'
  retrain: true
ts:
  name: 'test3'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  d_model: 32
  n_head: 4
  hidden_size: 64
  dropout_rate: 0.25
  n_layer_decoder: 2
  use_norm: True
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.PReLU
  class_strategy: 'average' #projection/average/cls_token

train_config:
  batch_size: 128
  max_epochs: 600
            
