# @package _global_

model:
  type: 'patchtst'
  retrain: true
ts:
  name: 'prova2'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  d_model: 8
  kernel_size: 3
  decomposition: false
  n_layer: 3
  patch_len: 2
  n_head: 2
  stride: 1 #non overlapping?
  dropout_rate: 0.2
  hidden_size: 16
  optim: torch.optim.Adam
  activation: torch.nn.GELU
  persistence_weight: 1
  loss_type: 'mse'
  remove_last: false

train_config:
  batch_size: 32
  max_epochs: 2000
            
