# @package _global_
ts:
  version: 1
  name: stacked
  type: stacked
  enrich: ['hour']
  use_covariates: false ##does not matter but it is mandatory
  
model:
  type: linear
  retrain: true

##where are the initial model
stack:
  #models: config_test
  models: ['config_incube/config_used/tft2_test_1_loss_type=std_normpersistence_weight=1.yaml','config_incube/config_used/crossformer_test_1_loss_type=std_penpersistence_weight=10.yaml']
  dirpath: "/home/agobbi/Projects/ExpTS/incube"
  set: 'validation'
  name: 'prova'
  rescaling: true
  batch_size: 64


model_configs:
  quantiles: []
  cat_emb_dim: 6
  kernel_size: 3
  sum_emb: true
  hidden_size: 1024
  kind: 'linear'
  dropout_rate: 0.05
  use_bn: false  
  optim: torch.optim.Adam
  activation: torch.nn.ReLU
  persistence_weight: 0.01
  loss_type: 'l1'



split_params:
  perc_train: 0.8
  perc_valid: 0.2
  past_steps: null
  starting_point: null
  future_steps: null


train_config:
  batch_size: 32
  max_epochs: 200

