# @package _global_

model:
  type: 'tft'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true

split_params:
  shift: 0

model_configs:
  d_model: 32 # tried 32, 64, 128
  num_heads: 4
  dropout: 0.3
  head_size: 16
  fw_exp: 3
  n_layer_encoder: 3
  n_layer_decoder: 3
  num_layers_RNN: 3
  use_target_past: True # True is better
  use_yprec_fut: True # True is really better
# first run done with wd = 0,01; but now set to 0.0

train_config:
  batch_size: 128 # 256 seems too high
  max_epochs: 250
