# @package _global_

model:
  type: 'tft'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true

split_params:
  shift: 0

model_configs: #
  d_model: 128
  num_heads: 16
  dropout: 0.3
  head_size: 8
  fw_exp: 2
  n_layer_encoder: 2
  n_layer_decoder: 2
  num_layers_RNN: 2
  use_target_past: True
  use_yprec_fut: False


train_config:
  batch_size: 256
  max_epochs: 5
                             
