# @package _global_

model:
  type: 'tft'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true

split_params:
  shift: 0

model_configs:
  d_model: 128
  num_heads: 4
  dropout: 0.3
  head_size: 64
  fw_exp: 2
  n_layer_encoder: 3
  n_layer_decoder: 3
  num_layers_RNN: 3
  use_target_past: False
  use_yprec_fut: False

train_config:
  batch_size: 256
  max_epochs: 100
