models: ['config_used_traffic/attention.yaml','config_used_traffic/persistent.yaml','config_used_traffic/linear.yaml','config_used_traffic/dlinear.yaml','config_used_traffic/nlinear.yaml','config_used_traffic/lstm.yaml','config_used_traffic/gru.yaml']
#models: ['config_used_traffic/linear.yaml']
dirpath: "/home/agobbi/Projects/ExpTSTraffic"
set: 'test'
name: 'prova'
rescaling: false