# @package _global_

model:
  type: 'diffusion'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['dow','hour']
  use_covariates: false

model_configs:
  d_model: 256
  diffusion_steps: 20
  beta: 0.1
  sigma: 1
  inference_out_from_sub_net: False
  d_head: 128
  n_head: 16
  optim: torch.optim.SGD
  dropout_rate: 0.3
  persistence_weight: 0.010
  loss_type: 'l1'


train_config:
  batch_size: 64
  max_epochs: 800
            
