# @package _global_

model:
  type: 'diffusion'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['dow','hour']
  use_covariates: false

model_configs:
  d_model: 128
  diffusion_steps: 100
  beta: 0.03
  sigma: 1
  inference_out_from_sub_net: True
  d_head: 128
  n_head: 8
  optim: torch.optim.Adam
  dropout_rate: 0.5
  persistence_weight: 0.010
  loss_type: 'l1'


train_config:
  batch_size: 64
  max_epochs: 2000
            
