# @package _global_

model:
  type: 'diffusion'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['dow','hour']
  use_covariates: false

model_configs:
  d_model: 64
  diffusion_steps: 20
  beta: 0.1
  sigma: 1
  inference_out_from_sub_net: True
  d_head: 64
  n_head: 8
  optim: torch.optim.Adam
  dropout_rate: 0.2
  persistence_weight: 0.010
  loss_type: 'l1'


train_config:
  batch_size: 64
  max_epochs: 800
            
