# @package _global_

model:
  type: 'mymodel'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true

model_configs:
  cat_emb_dim: 64
  hidden_RNN: 128
  num_layers_RNN: 4
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.2
  use_bn: true
  optim: torch.optim.SGD
  activation: torch.nn.PReLU
  loss_type: 'normal'

train_config:
  batch_size: 128
  max_epochs: 200
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
