# @package _global_

model:
  type: 'linear'
  retrain: true
ts:
  name: 'n'
  version: 1
  enrich: ['month']
  use_covariates: true

model_configs:
  cat_emb_dim: 128
  kernel_size: 9
  sum_emb: true
  hidden_size: 512
  kind: 'nlinear'
  dropout_rate: 0.25
  use_bn: false  
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.01
  loss_type: 'l1'
  
train_config:
  batch_size: 128
  max_epochs: 500
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
  