# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['month']
  use_covariates: false
  silly: false

model_configs:
  d_model: 256
  d_head: 48
  n_head: 4
  num_layers_RNN: 2
  optim: torch.optim.Adam
  dropout_rate: 0.15
  persistence_weight: 0.010
  loss_type: 'l1'


train_config:
  batch_size: 50
  max_epochs: 300
            
