# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['month']
  use_covariates: false
  silly: false

model_configs:
  d_model: 128
  d_head: 64
  n_head: 12
  num_layers_RNN: 4
  optim: torch.optim.Adam
  dropout_rate: 0.5
  persistence_weight: 10
  loss_type: 'std_penalization'


train_config:
  batch_size: 50
  max_epochs: 300
            
