
defaults:
  - _self_  
  - override hydra/launcher: submitit_slurm #joblib 

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 6000
    partition: gpu-A40 #A40 #gpu-V100
    mem_gb: 8
    nodes: 1
    gres: gpu:1
    array_parallelism: 10 ##altrimenti roldano si arrabbia
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    setup:
      - conda activate tt  
 

output_subdir: null 
