#models: ['config_used/attention.yaml','config_used/persistent.yaml','config_used/linear.yaml','config_used/dlinear.yaml','config_used/nlinear.yaml','config_used/lstm.yaml','config_used/gru.yaml']
#models: 'config_edison'
models:  ['config_edison/config_used/linear_1.yaml','config_edison/config_used/persistent_1.yaml','config_edison/config_used/nlinear_1.yaml','config_edison/config_used/dlinear_1.yaml','config_edison/config_used/gru_1.yaml','config_edison/config_used/lstm_1.yaml','config_edison/config_used/mymodel_mymodel_exp_noweight_1.yaml']
#,'config_edison/config_used/gru_1.yaml','config_edison/config_used/lstm_1.yaml']

dirpath: "/home/agobbi/Projects/ExpTS/edison"
set: 'test'
name: 'prova'
rescaling: true
batch_size: 64

defaults:
  - _self_
  - override hydra/launcher: submitit_slurm 

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 6000
    partition: gpu-A40
    mem_gb: 16
    nodes: 1
    gres: gpu:1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    setup:
      - conda activate tt     