models: config_paper_persistence
#models: ['config_used/linear.yaml']
dirpath: /storage/DSIP/agobbi/Projects/ExpTS/paper_persistence_v2_synthetic

set: 'test'
name: 'synthetic'
rescaling: true

defaults:
  - _self_
  - override hydra/launcher: submitit_slurm 



hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 6000
    partition: h100
    mem_gb: 8
    nodes: 1
    gres: gpu:h100_1g.20gb
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    setup:
      - source /storage/DSIP/agobbi/Projects/DSIPTS/dsipts/.venv/bin/activate  
