dataset:
  dataset: 'venice'  
  path: '/home/andrea/TsEXP/data'

scheduler_config:
  gamma: 0.75
  step_size: 2500

optim_config:
  lr: 0.00005
  weight_decay: 0.00

model_configs:
  past_steps: 168
  future_steps: 48
  quantiles: []
  past_channels : null #dataset dependent
  future_channels : null #dataset dependent
  embs: null #dataset dependent
  out_channels: null #dataset dependent

split_params:
  perc_train: 0.6
  perc_valid: 0.2
  range_train: ['2010-01-01 00:00:00','2018-01-01 00:00:00']
  range_validation: ['2018-01-01 00:00:00','2020-01-01 00:00:00'] 
  range_test: ['2020-01-01 00:00:00','2022-01-01 00:00:00']
  shift: 0
  starting_point: null
  skip_step: 1
  past_steps: model_configs@past_steps 
  future_steps: model_configs@future_steps


train_config:
  dirpath: "/home/andrea/TsEXP/" 
  num_workers: 0
  auto_lr_find: true
  devices: [0]                   

inference:
  output_path: "/home/andrea/TsEXP/" 
  load_last: true
  batch_size: 200 
  num_workers: 4
  set: "validation"
  rescaling: true

defaults:
  - _self_
  - architecture: null 
  - override hydra/launcher: joblib 

hydra:
  launcher: #joblib
    n_jobs:   2 
  output_subdir: null 
  sweeper:
    params:
      architecture: glob(*) 
