# @package _global_

model:
  type: 'diffusion'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  d_model: 64
  learn_var: True
  cosine_alpha: True
  diffusion_steps: 50
  beta: 0.03
  gamma: 0.01
  n_layers_RNN: 4
  d_head: 32
  n_head: 8
  dropout_rate: 0.0
  activation: 'torch.nn.GELU'
  subnet: 3
  optim: torch.optim.Adam
  perc_subnet_learning_for_step: 0.1
  persistence_weight: 0.010
  loss_type: 'l1'

train_config:
  batch_size: 128 
  max_epochs: 400
