# @package _global_

model:
  type: 'dilated_conv'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  cat_emb_dim: 128
  hidden_RNN: 64
  num_layers_RNN: 2
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  use_bn: false
  dropout_rate: 0.5
  optim: torch.optim.Adam
  activation: torch.nn.GELU
  persistence_weight: 0.010
  loss_type: 'l1'
  use_cumsum: true

train_config:
  batch_size: 64
  max_epochs: 1000
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
