# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather_d'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 32
  kernel_size_encoder: 5
  sum_emb: true
  hidden_size: 256
  kind: 'dlinear'
  dropout_rate: 0.1
  use_bn: true  
  activation: 'SELU'

train_config:
  batch_size: 256
  max_epochs: 250           
  gradient_clip_val: 5.0
  gradient_clip_algorithm: 'value'