# @package _global_

model:
  type: 'informer'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: false

model_configs:
  d_model: 128
  hidden_size: 128
  n_layer_encoder: 2
  n_layer_decoder: 2
  num_heads: 2
  dropout_rate: 0.5
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  remove_last: true

train_config:
  batch_size: 128
  max_epochs: 1000
            
