# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 32
  kernel_size_encoder: 5
  sum_emb: true
  hidden_size: 256
  kind: 'linear'
  dropout_rate: 0.2
  use_bn: true  
  activation: 'relu'

train_config:
  batch_size: 256
  max_epochs: 250
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
