# @package _global_

model:
  type: 'rnn'
  retrain: true
ts:
  name: 'lstm'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 32
  hidden_RNN: 128
  num_layers_RNN: 2
  kernel_size: 5
  kind: 'lstm'
  sum_emb: true
  use_bn: true  
  optim: torch.optim.SGD
  activation: torch.nn.PReLU
  dropout_rate: 0.2
  persistence_weight: 0.2
  loss_type: 'l1'

train_config:
  batch_size: 128
  max_epochs: 250
            
