# @package _global_

model:
  type: 'mymodel'
  
ts:
  name: 'weather_mymodel'
  version: 2
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 64
  hidden_RNN: 512
  num_layers_RNN: 2
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.2
  use_bn: false
  activation: 'relu'
  loss_type: 'linear_penalization'

train_config:
  batch_size: 128
  max_epochs: 150
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
