# @package _global_

model:
  type: 'mymodel'
  
ts:
  name: 'weather_mymodel'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 64
  hidden_RNN: 2048
  num_layers_RNN: 2
  kernel_size_encoder: 3
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.25


train_config:
  batch_size: 256
  max_epochs: 250
            
