# @package _global_

model:
  type: 'mymodel'
  
ts:
  name: 'weather_mymodel'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 64
  hidden_RNN: 1024
  num_layers_RNN: 2
  kernel_size_encoder: 3
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.05
  use_bn: false
  activation: 'relu'

train_config:
  batch_size: 256
  max_epochs: 250
  gradient_clip_val: 0.0
  gradient_clip_algorithm: 'value'
