# @package _global_

model:
  type: 'mymodel'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 128
  hidden_RNN: 128
  num_layers_RNN: 2
  kernel_size: 3
  kind: 'gru'
  sum_emb: true
  use_bn: true
  optim: torch.optim.SGD
  activation: torch.nn.PReLU
  persistence_weight: 1.0
  loss_type: 'l1'
  remove_last: true

train_config:
  batch_size: 128
  max_epochs: 500
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
