# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather_n'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 32
  kernel_size_encoder: 5
  sum_emb: true
  hidden_size: 256
  kind: 'nlinear'
  dropout_rate: 0.1
  use_bn: false
  activation: 'prelu'

train_config:
  batch_size: 256
  max_epochs: 250
  gradient_clip_val: 0.0
  gradient_clip_algorithm: 'value'
  