# @package _global_

model:
  type: 'patchtst'
  retrain: true
ts:
  name: 'weather'
  version: 1
  enrich: ['dow','hour']
  use_covariates: true


model_configs:
  d_model: 128
  kernel_size: 7
  decomposition: false
  n_layer: 3
  patch_len: 8
  n_head: 16
  stride: 8 #non overlapping?
  dropout_rate: 0.2
  hidden_size: 256
  optim: torch.optim.Adam
  activation: torch.nn.GELU
  persistence_weight: 1
  loss_type: 'mse'
  remove_last: false

train_config:
  batch_size: 128
  max_epochs: 600
            
