# @package _global_

model:
  type: 'patchtst'
  retrain: true
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  d_model: 64
  kernel_size: 7
  decomposition: false
  n_layer: 3
  patch_len: 8
  n_head: 16
  stride: 8 #non overlapping?
  dropout_rate: 0.2
  hidden_size: 128
  optim: torch.optim.Adam
  activation: torch.nn.GELU
  persistence_weight: 1
  loss_type: 'mse'
  remove_last: false

train_config:
  batch_size: 64
  max_epochs: 300
            
