# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  d_model: 64
  d_head: 32
  n_head: 8
  num_layers_RNN: 2
  optim: torch.optim.Adam
  dropout_rate: 0.55
  persistence_weight: 1
  loss_type: 'mse'

train_config:
  batch_size: 32
  max_epochs: 300
            
