# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'weather'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  d_model: 128
  d_head: 128
  n_head: 4
  num_layers_RNN: 8
  optim: torch.optim.Adam
  dropout_rate: 0.25
  persistence_weight: 0.010
  loss_type: 'std_penalization'

train_config:
  batch_size: 64
  max_epochs: 500
            
