# @package _global_

model:
  type: 'linear'
  retrain: true
ts:
  name: 'd'
  version: 1
  enrich: []
  use_covariates: true

model_configs:
  cat_emb_dim: 8
  kernel_size: 3
  sum_emb: true
  hidden_size: 2048
  kind: 'dlinear'
  dropout_rate: 0.25
  use_bn: true,
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.1
  loss_type: 'l1'
  simple: false

train_config:
  batch_size: 64
  max_epochs: 500          
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'