# @package _global_

model:
  type: 'itransformer'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  d_model: 256
  n_head: 7
  hidden_size: 128
  dropout_rate: 0.1
  n_layer_decoder: 2
  use_norm: True
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  activation: torch.nn.ReLU
  class_strategy: 'projection' #projection/average/cls_token

train_config:
  batch_size: 128
  max_epochs: 600
            
