#models: ['config_used/attention.yaml','config_used/persistent.yaml','config_used/linear.yaml','config_used/dlinear.yaml','config_used/nlinear.yaml','config_used/lstm.yaml','config_used/gru.yaml']
models: 'config_weather'
dirpath: "/home/agobbi/Projects/ExpTS/weather"
set: 'test'
name: 'prova'
rescaling: false
batch_size: 32
