#models: ['config_used/attention.yaml','config_used/persistent.yaml','config_used/linear.yaml','config_used/dlinear.yaml','config_used/nlinear.yaml','config_used/lstm.yaml','config_used/gru.yaml']
#models: 'config_weather'
models: ['config_used/vva_test_1_d_model=192max_voc_size=128n_heads=6.yaml']
dirpath: "/home/agobbi/Projects/ExpTS/weather"
set: 'test'
name: 'prova'
rescaling: true
batch_size: 32

defaults:
  - _self_
  - override hydra/launcher: submitit_slurm 

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 6000
    partition: gpu-A40
    mem_gb: 8
    nodes: 1
    gres: gpu:1
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    setup:
      - conda activate tt     