# @package _global_

model:
  type: 'crossformer'
  retrain: true
ts:
  name: ${dataset.dataset}
  version: 1
  enrich: ['hour']
  use_covariates: true


model_configs:
  d_model: 64
  hidden_size: 64
  n_layer_encoder: 4
  n_head: 4
  dropout_rate: 0.5
  win_size: 4
  seg_len: 3
  factor: 1
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'

train_config:
  batch_size: 64
  max_epochs: 100
            
