# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather_n'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 16
  kernel_size_encoder: 5
  sum_emb: true
  hidden_size: 256
  kind: 'nlinear'

train_config:
  batch_size: 256
  max_epochs: 250
