# @package _global_

model:
  type: 'rnn'
  
ts:
  name: 'weather_gru'
  version: 1
  enrich: ['hour']
  use_covariates: true

model_configs:
  cat_emb_dim: 64
  hidden_RNN: 128
  num_layers_RNN: 4
  kernel_size: 5
  kind: 'gru'
  loss_type: 'l1'
  sum_emb: true


train_config:
  batch_size: 64
  max_epochs: 100
            
