# @package _global_

model:
  type: 'attention'
  
ts:
  name: 'attention'
  version: 1
  enrich: []
  use_covariates: true

split_params:
  shift: 1 ##this will use the shifted data and it is more like the original one

model_configs:
  d_model: 256
  cat_emb_dim: 64
  num_heads: 16
  dropout: 0.3
  n_layer_encoder: 12
  n_layer_decoder: 8


train_config:
  batch_size: 256
  max_epochs: 250
                             
