# @package _global_

model:
  type: 'mymodel'
  retrain: true
ts:
  name: 'mymodel'
  version: 1
  enrich: []
  use_covariates: true

model_configs:
  cat_emb_dim: 32
  hidden_RNN: 128
  num_layers_RNN: 6
  kernel_size: 5
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.1
  use_bn: true
  use_glu: false
  glu_percentage: 0.2
  quantiles: [0.1,0.5,0.9]

  activation: 'relu'
  loss_type: 'linear_penalization'

train_config:
  batch_size: 128
  max_epochs: 250
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
