# @package _global_

model:
  type: 'mymodel'
  retrain: true
ts:
  name: 'mymodel_exp_noweight'
  version: 1
  enrich: []
  use_covariates: true

model_configs:
  cat_emb_dim: 2048
  hidden_RNN: 2048
  num_layers_RNN: 32
  kernel_size: 5
  kind: 'gru'
  sum_emb: true
  persistence_weight: 0.0
  use_bn: true
  use_glu: false
  glu_percentage: 1.2
  quantiles: []
  #[0.1,0.5,0.9]
  optim: torch.optim.SGD
  activation: torch.nn.PReLU
  loss_type: 'exponential_penalization'
  dropout_rate: 0.0
  
train_config:
  batch_size: 50
  max_epochs: 250
  gradient_clip_val: null
  gradient_clip_algorithm: 'norm'
