# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'tft'
  version: 1
  enrich: []
  use_covariates: true

split_params:
  shift: 0

model_configs:
  d_model: 64
  num_heads: 4
  dropout: 0.3
  head_size: 64
  fw_exp: 3
  n_layer_encoder: 5
  n_layer_decoder: 6
  num_layers_RNN: 6
  kind: lstm
  use_target_past: True
  use_yprec_fut: True
  quantiles: [0.1,0.5,0.9]

train_config:
  batch_size: 64
  max_epochs: 250
                             
