# @package _global_

model:
  type: 'tft'
  
ts:
  name: 'tft'
  version: 1
  enrich: []
  use_covariates: true

split_params:
  shift: 0

model_configs:
  d_model: 64
  num_heads: 4
  dropout: 0.3
  head_size: 64
  fw_exp: 3
  n_layer_encoder: 3
  n_layer_decoder: 3
  num_layers_RNN: 3
  use_target_past: True
  use_yprec_fut: True


train_config:
  batch_size: 128
  max_epochs: 150
                             
