# @package _global_

model:
  type: 'd3vae'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: true

split_params:
  shift: 0 ##this will use the shifted data and it is more like the original one

model_configs:
  embedding_dimension: 14
  scale: 0.1
  hidden_size: 64
  num_layers: 2
  dropout_rate: 0.1
  diff_steps: 80
  loss_type: 'kl'
  beta_end: 0.01
  beta_schedule: 'linear'
  channel_mult :  2
  mult: 1
  num_preprocess_blocks: 1
  num_preprocess_cells: 3
  num_channels_enc: 32
  arch_instance :  'res_mbconv'
  num_latent_per_group: 8
  num_channels_dec: 32
  groups_per_scale: 2
  num_postprocess_blocks: 1
  num_postprocess_cells: 2
  beta_start: 0


train_config:
  batch_size: 256
  max_epochs: 2
                             
