# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather_d'
  version: 1
  enrich: ['hour']
  use_covariates: false

model_configs:
  cat_emb_dim: 4
  kernel_size: 3
  sum_emb: true
  hidden_size: 12
  kind: 'dlinear'
  optim: torch.optim.SGD
  activation: torch.nn.LeakyReLU

train_config:
  batch_size: 256
  max_epochs: 2
                   
