# @package _global_

model:
  type: 'linear'
  
ts:
  name: 'weather_d'
  version: 1
  enrich: ['hour']
  use_covariates: false

model_configs:
  cat_emb_dim: 16
  kernel_size_encoder: 15
  sum_emb: true
  hidden_size: 256
  kind: 'dlinear'


train_config:
  batch_size: 256
  max_epochs: 5
                   
