# @package _global_

model:
  type: 'linear'
  retrain: true
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: false
  

model_configs:
  cat_emb_dim: 16
  kernel_size: 5
  sum_emb: true
  hidden_size: 8
  kind: 'linear'
  dropout_rate: 0.1
  use_bn: false  
  optim: torch.optim.Adam
  activation: torch.nn.PReLU
  persistence_weight: 0.010
  loss_type: 'l1'
  

train_config:
  batch_size: 256
  max_epochs: 5

              
