# @package _global_
  
model:
  type: 'rnn'
  
ts:
  name: 'weather_lstm'
  version: 1
  enrich: ['hour']
  use_covariates: false
  
model_configs:
  cat_emb_dim: 16
  hidden_RNN: 12
  num_layers_RNN: 3
  kernel_size: 5
  kind: 'lstm'
  sum_emb: true
  optim: torch.optim.SGD
  activation: torch.nn.SELU
  
train_config:
  batch_size: 256
  max_epochs: 3
              
