# @package _global_

model:
  type: 'linear'
  retrain: true
  
ts:
  name: 'weather_n'
  version: 1
  enrich: ['hour']
  use_covariates: false
  
model_configs:
  cat_emb_dim: 16
  kernel_size: 5
  sum_emb: true
  hidden_size: 24
  kind: 'nlinear'

train_config:
  batch_size: 256
  max_epochs: 3
