# @package _global_

model:
  type: 'persistent'
  
ts:
  name: 'weather'
  version: 1
  enrich: ['hour']
  use_covariates: false

split_params:
  shift: 0

train_config:
  batch_size: 256
  max_epochs: 0
                             
