# @package _global_

model:
  type: 'tft'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true


model_configs:
  d_model: 4
  d_head: 4
  n_head: 4
  num_layers_RNN: 8
  optim: torch.optim.Adam
  dropout_rate: 0.5
  persistence_weight: 0.010
  loss_type: 'l1'

train_config:
  batch_size: 128
  max_epochs: 3
            
