# @package _global_

model:
  type: 'tide'
  retrain: true
ts:
  name: 'test'
  version: 1
  enrich: ['dow','hour']
  use_covariates: true

model_configs:
  hidden_size: 4
  d_model: 4
  activation: 'torch.nn.GELU'
  n_add_enc: 1
  n_add_dec: 1
  quantiles: [0.1, 0.5, 0.9]
  optim: torch.optim.Adam
  dropout_rate: 0.2
  persistence_weight: 0.010
  loss_type: 'l1'

train_config:
  batch_size: 128
  max_epochs: 3
