# @package _global_

model:
  type: 'timekan'
  retrain: true
  restart: false
ts:
  name: 'test'
  version: 1
  enrich: ['hour']
  use_covariates: true
  use_future_covariates: true
  silly: false
  
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  down_sampling_window: 2
  e_layers: 2
  moving_avg: 3
  down_sampling_layers: 2
  d_model: 6
  begin_order: 2
  use_norm: true
  optim: torch.optim.AdamW
  persistence_weight: 0.010
  loss_type: 'l1'
  quantiles: [0.1,0.5,0.9]
train_config:
  batch_size: 32
  max_epochs: 1
         