dataset:
  dataset: null
  path: /storage3/DSIP/agobbi/Projects/ExpTS/data
  
ts:
  name: 'test'
  version: 1
  enrich: []
  use_covariates: true
  use_future_covariates: false

scheduler_config:
  gamma: 1.0
  step_size: 100

optim_config:
  lr: 0.00025
  weight_decay: 0.00001

model_configs:
  past_steps: 144
  future_steps: 60
  quantiles: []
  past_channels : null #dataset dependent
  future_channels : null #dataset dependent
  embs_past: null #dataset dependent
  embs_fut: null #dataset dependent
  out_channels: null #dataset dependent

stack:
  dirpath: null

split_params:
  perc_train: 0.7
  perc_valid: 0.1
  range_train: null
  range_validation: null 
  range_test: null
  shift: 0
  starting_point: null
  skip_step: 1
  past_steps: model_configs@past_steps 
  future_steps: model_configs@future_steps
  scaler: 'StandardScaler()' ## or sklearn.preprocessing.StandardScaler()
train_config:
  dirpath: /storage3/DSIP/agobbi/Projects/ExpTS/paper_persistence
  num_workers: 0
  auto_lr_find: false
  devices: [0]                   
  seed: 42    
inference:
  output_path: /storage3/DSIP/agobbi/Projects/ExpTS/paper_persistence
  load_last: true
  batch_size: 200 
  num_workers: 4
  set: "test"
  rescaling: true

defaults:
  - _self_
  - architecture: null 
  - override hydra/launcher: submitit_slurm #joblib 

hydra:
  launcher:
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    timeout_min: 9000
    partition: gpu-V100 #A40 #gpu-V100
    mem_gb: 4
    nodes: 1
    gres: shard:1  #gpu:1
    array_parallelism: 10 ##
    name: ${hydra.job.name}
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    setup:
      - source /storage3/DSIP/agobbi/Projects/timeseries/dsipts/.venv/bin/activate  


  output_subdir: null 
  sweeper:
    params:
      architecture: glob(*) #architecture


#python train.py --config-dir=config_paper_persistence --config-name=config_slurm architecture=itransformer,simple train_config.auto_lr_find=true,false model_configs.dropout_rate=0.0,0.1 -m