# @package _global_

model:
  type: 'timesnet'
  retrain: true
  restart: false
ts:
  name: 'weather'
  version: 1
  enrich: [hour]
  use_covariates: true
  silly: false
  use_future_covariates: false
  check: true
  
model_configs:
  use_classical_positional_encoder: true 
  emb_dim: 16 
  reduction_mode: mean 
  e_layers: 4
  d_model: 192
  top_k: 8
  d_ff: 256
  num_kernels: 3
  optim: torch.optim.Adam
  persistence_weight: 0.010
  loss_type: 'l1'
  quantiles: []
train_config:
  batch_size: 64
  max_epochs: 1000
         